version: '3.8'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi-app
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - JWT_SECRET=your-jwt-secret-here
      - ADMIN_JWT_SECRET=your-admin-jwt-secret-here
      - TRANSFER_TOKEN_SALT=your-transfer-token-salt-here
      - API_TOKEN_SALT=your-api-token-salt-here
    volumes:
      - strapi_data:/app/public/uploads
    depends_on:
      - postgres
    networks:
      - strapi-network

  postgres:
    image: postgres:15-alpine
    container_name: strapi-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi-network

volumes:
  strapi_data:
  postgres_data:

networks:
  strapi-network:
    driver: bridge
